apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "1800" #necessario porque a imagem ubuntu termina imediatamente apos iniciar
    resources: #limite maximo de recursos que o pod pode usar
      limits:
        cpu: "0.3"
        memory: "128Mi" 
      requests: #garante recursos minimos para o pod ser agendado
        cpu: "0.1"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
